const SUPABASE_URL='https://yonxttybnkvxwnbhzwyi.supabase.co';
const SUPABASE_KEY='sb_publishable_EC6Tm1kbWuPEPtfeeJED9Q_6dbqOZVh';
const OFFICE_EMAIL='silambarasan2453@gmail.com';
const sessionKey='chennai-goods-session';
let token=sessionStorage.getItem(sessionKey),shipments=[],action=null,editingId=null;
const $=s=>document.querySelector(s),today=()=>new Date().toISOString().slice(0,10);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>d?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${d}T00:00:00`)):'—';
const statusOf=s=>s.accounts_date?'Completed':s.delivery_date?'Accounts pending':'Pending delivery';
function headers(extra={}){return {'apikey':SUPABASE_KEY,'Authorization':`Bearer ${token}`,...extra}}
async function api(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:headers(options.headers)});if(!r.ok){const x=await r.json().catch(()=>({message:r.statusText}));throw new Error(x.message||x.hint||'Cloud connection failed.')}return r.status===204?null:r.json()}
async function load(){const select='*,parties(name),branches(name),stock_checks(checked_date,check_status)';const rows=await api(`shipments?${new URLSearchParams({select,order:'created_at.desc'})}`);shipments=rows.map(s=>{const checks=[...(s.stock_checks||[])].sort((a,b)=>b.checked_date.localeCompare(a.checked_date));const last=checks[0];return {...s,party_name:s.parties?.name||'',branch_name:s.branches?.name||'',stock_status:last?.check_status||null,stock_checked_date:last?.checked_date||null}});render()}
async function getOrCreate(table,name){const q=new URLSearchParams({select:'id',name:`eq.${name}`,limit:'1'});let rows=await api(`${table}?${q}`);if(rows[0])return rows[0].id;rows=await api(table,{method:'POST',headers:{'Content-Type':'application/json','Prefer':'return=representation'},body:JSON.stringify([{name,is_active:true}])});return rows[0].id}
function renderOptions(){const p=[...new Set(shipments.map(s=>s.party_name))].sort(),b=[...new Set(shipments.map(s=>s.branch_name))].sort();$('#party-list').innerHTML=p.map(x=>`<option value="${safe(x)}">`).join('');$('#branch-list').innerHTML=b.map(x=>`<option value="${safe(x)}">`).join('')}
function button(type,s,label,kind=''){return `<button class="action ${kind}" data-action="${type}" data-id="${s.id}">${label}</button>`}
function row(s,mode){const st=statusOf(s),cl=st==='Completed'?'completed':st==='Accounts pending'?'accounts':'pending';let c='';if(mode==='workflow')c=st==='Pending delivery'?button('deliver',s,'Mark delivery'):st==='Accounts pending'?`${button('accounts',s,'Enter A/C date')} ${button('undelivered',s,'Mark undelivered','light')}`:button('undelivered',s,'Mark undelivered','light');if(mode==='all')c=`${st!=='Pending delivery'?button('undelivered',s,'Mark undelivered','light'):''} ${button('edit',s,'Edit','light')} ${button('delete',s,'Delete','danger')}`;return `<tr><td><b>${safe(s.lr_number)}</b></td><td>${safe(s.party_name)}</td><td>${safe(s.branch_name)}</td><td>${safe(s.quantity)}</td><td>₹${Number(s.amount).toLocaleString('en-IN')}</td><td>${safe(s.remarks)||'—'}</td><td>${date(s.accounts_date)}</td><td>${date(s.received_date)}</td><td><span class="badge ${cl}">${st}</span></td>${mode?`<td class="actions">${c}</td>`:''}</tr>`}
function table(data,target,mode=false){const h='<th>LR no.</th><th>Party</th><th>From</th><th>Qty</th><th>Amount</th><th>Remarks</th><th>A/C date</th><th>Received</th><th>Status</th>';$(target).innerHTML=data.length?`<div class="table-wrap"><table><thead><tr>${h}${mode?'<th></th>':''}</tr></thead><tbody>${data.map(s=>row(s,mode)).join('')}</tbody></table></div>`:'<p class="empty">No shipments found.</p>'}
function stockTable(data){$('#stock-table').innerHTML=data.length?`<div class="table-wrap"><table><thead><tr><th>LR no.</th><th>Party</th><th>From</th><th>Qty</th><th>Remarks</th><th>Last check</th><th>Godown status</th><th></th></tr></thead><tbody>${data.map(s=>`<tr><td><b>${safe(s.lr_number)}</b></td><td>${safe(s.party_name)}</td><td>${safe(s.branch_name)}</td><td>${safe(s.quantity)}</td><td>${safe(s.remarks)||'—'}</td><td>${date(s.stock_checked_date)}</td><td>${s.stock_status?`<span class="badge ${s.stock_status==='IN GODOWN'?'completed':'pending'}">${s.stock_status==='IN GODOWN'?'In godown':'Not found'}</span>`:'<span class="muted">Not checked</span>'}</td><td class="actions">${button('in-godown',s,'In godown')}${button('not-found',s,'Not found','danger')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">There are no undelivered goods to check.</p>'}
function render(){const pending=shipments.filter(s=>!s.delivery_date),accounts=shipments.filter(s=>s.delivery_date&&!s.accounts_date),done=shipments.filter(s=>s.accounts_date);$('#stat-received').textContent=shipments.filter(s=>s.received_date===today()).length;$('#stat-delivery').textContent=pending.length;$('#stat-accounts').textContent=accounts.length;$('#stat-completed').textContent=done.filter(s=>s.accounts_date===today()).length;$('#delivery-count').textContent=pending.length||'';$('#accounts-count').textContent=accounts.length||'';table(shipments.slice(0,6),'#recent-table');table(pending,'#delivery-table','workflow');table(accounts,'#accounts-table','workflow');table(shipments,'#all-table','all');stockTable(pending);renderOptions()}
function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const n={dashboard:['Good morning','CHENNAI BRANCH'],receive:[editingId?'Edit shipment':'Receive goods','NEW GOODS ENTRY'],delivery:['Pending delivery','CHENNAI BRANCH'],accounts:['Accounts pending','CHENNAI BRANCH'],stock:['Godown stock check','DAILY PHYSICAL VERIFICATION'],all:['All shipments','CHENNAI BRANCH']};$('#page-title').textContent=n[page][0];$('#page-kicker').textContent=n[page][1];$('#receive-button').style.display=page==='receive'?'none':''}
function resetForm(){editingId=null;const f=$('#shipment-form');f.reset();f.received_date.value=today();f.querySelector('[type=submit]').textContent='Save goods receipt';$('#form-message').textContent=''}
function editShipment(s){editingId=s.id;const f=$('#shipment-form');['received_date','lr_number','party_name','branch_name','quantity','amount','payment_type','remarks'].forEach(k=>f.elements[k].value=s[k]??'');f.querySelector('[type=submit]').textContent='Save changes';showPage('receive')}
async function cloudAction(fn){try{await fn();await load()}catch(e){alert(e.message)}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#login-message'),password=$('#login-password').value;msg.textContent='Signing in…';try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:OFFICE_EMAIL,password})});const d=await r.json();if(!r.ok){msg.textContent=d.error_description||'Sign-in failed.';return}token=d.access_token;sessionStorage.setItem(sessionKey,token);$('#login-screen').style.display='none';
$('#app-shell').style.display='block';

load().catch(e=>{
    console.error('Dashboard loading failed:', e);
    $('#login-message').textContent='Login successful, but dashboard could not load.';
});}catch(error){msg.textContent='Unable to reach Supabase. Check the internet connection and try agaif(token){
    $('#login-screen').style.display='none';
    $('#app-shell').style.display='block';

    load().catch(e=>{
        console.error('Dashboard loading failed:', e);
        $('#sign-out').click();
    });
}in.'}});
$('#sign-out').addEventListener('click',()=>{token=null;sessionStorage.removeItem(sessionKey);$('#app-shell').hidden=true;$('#login-screen').hidden=false;$('#login-password').value=''});
document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.page==='receive')resetForm();showPage(b.dataset.page)}));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));$('#receive-button').addEventListener('click',()=>{resetForm();showPage('receive')});resetForm();
$('#shipment-form').addEventListener('submit',e=>cloudAction(async()=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),party_id=await getOrCreate('parties',d.party_name.trim()),from_branch_id=await getOrCreate('branches',d.branch_name.trim());const payload={received_date:d.received_date,lr_number:d.lr_number.trim(),party_id,from_branch_id,quantity:Number(d.quantity),amount:Number(d.amount),payment_type:d.payment_type,remarks:d.remarks||null};if(editingId)await api(`shipments?id=eq.${editingId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});else await api('shipments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify([payload])});resetForm();$('#form-message').textContent='Saved to cloud.'}));
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const s=shipments.find(x=>x.id===b.dataset.id),type=b.dataset.action;if(type==='edit'){editShipment(s);return}if(type==='delete'){if(confirm(`Delete LR ${s.lr_number}? This cannot be undone.`))cloudAction(()=>api(`shipments?id=eq.${s.id}`,{method:'DELETE'}));return}if(type==='undelivered'){if(confirm(`Mark LR ${s.lr_number} as undelivered? Its delivery and A/C dates will be removed.`))cloudAction(()=>api(`shipments?id=eq.${s.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({delivery_date:null,accounts_date:null})}));return}if(type==='in-godown'||type==='not-found'){cloudAction(()=>api('stock_checks?on_conflict=shipment_id,checked_date',{method:'POST',headers:{'Content-Type':'application/json','Prefer':'resolution=merge-duplicates'},body:JSON.stringify([{shipment_id:s.id,checked_date:today(),check_status:type==='in-godown'?'IN GODOWN':'NOT FOUND'}])}));return}action={type,shipment:s};$('#dialog-title').textContent=type==='deliver'?'Mark delivery':'Enter A/C date';$('#dialog-detail').textContent=`${s.lr_number} · ${s.party_name}`;$('#date-label').childNodes[0].nodeValue=type==='deliver'?'Delivery date':'A/C date';$('#action-date').min=type==='deliver'?s.received_date:s.delivery_date;$('#action-date').value=today();$('#date-dialog').showModal()});
$('#date-form').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();cloudAction(async()=>{const field=action.type==='deliver'?'delivery_date':'accounts_date';await api(`shipments?id=eq.${action.shipment.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({[field]:$('#action-date').value})});$('#date-dialog').close()})});
document.querySelectorAll('[data-search]').forEach(input=>input.addEventListener('input',()=>{const q=input.value.toLowerCase(),kind=input.dataset.search;let data=kind==='delivery'?shipments.filter(s=>!s.delivery_date):kind==='accounts'?shipments.filter(s=>s.delivery_date&&!s.accounts_date):kind==='stock'?shipments.filter(s=>!s.delivery_date):shipments;data=data.filter(s=>`${s.lr_number} ${s.party_name} ${s.branch_name} ${s.remarks||''}`.toLowerCase().includes(q));kind==='stock'?stockTable(data):table(data,`#${kind}-table`,kind==='all'?'all':'workflow')}));
if(token){$('#login-screen').hidden=true;$('#app-shell').hidden=false;load().catch(()=>$('#sign-out').click())}
